import { Match, Player } from "@/types";

export const samplePlayers: Player[] = [
    {
      id: "1",
      name: "Imran",
      ranking: 1,
      matchesPlayed: 8,
      lifetimeScore: 157,
      averageScore: 19.63,
      centuries: 0,
      fifties: 1,
      color: "#97ff1c",
    },
    {
      id: "2",
      name: "Awais",
      ranking: 2,
      matchesPlayed: 12,
      lifetimeScore: 245,
      averageScore: 20.42,
      centuries: 2,
      fifties: 3,
      color: "#4A235A",
    },
    {
      id: "3",
      name: "Asim",
      ranking: 3,
      matchesPlayed: 15,
      lifetimeScore: 312,
      averageScore: 20.8,
      centuries: 1,
      fifties: 4,
      color: "#eea200",
    },
    {
      id: "4",
      name: "Bilal",
      ranking: 4,
      matchesPlayed: 10,
      lifetimeScore: 198,
      averageScore: 19.8,
      centuries: 0,
      fifties: 2,
      color: "#b28ecb",
    },
    {
      id: "5",
      name: "Qaisar",
      ranking: 5,
      matchesPlayed: 6,
      lifetimeScore: 142,
      averageScore: 23.67,
      centuries: 1,
      fifties: 0,
      color: "#ef00ca",
    },
    {
      id: "6",
      name: "Farhan",
      ranking: 6,
      matchesPlayed: 7,
      lifetimeScore: 134,
      averageScore: 19.14,
      centuries: 0,
      fifties: 1,
      color: "#00bfff",
    },
    {
      id: "7",
      name: "Usman",
      ranking: 7,
      matchesPlayed: 11,
      lifetimeScore: 210,
      averageScore: 19.09,
      centuries: 1,
      fifties: 2,
      color: "#ff6f61",
    },
    {
      id: "8",
      name: "Kamran",
      ranking: 8,
      matchesPlayed: 9,
      lifetimeScore: 180,
      averageScore: 20.0,
      centuries: 0,
      fifties: 3,
      color: "#008080",
    },
    {
      id: "9",
      name: "Noman",
      ranking: 9,
      matchesPlayed: 5,
      lifetimeScore: 125,
      averageScore: 25.0,
      centuries: 1,
      fifties: 0,
      color: "#ff8c00",
    },
    {
      id: "10",
      name: "Rizwan",
      ranking: 10,
      matchesPlayed: 13,
      lifetimeScore: 260,
      averageScore: 20.0,
      centuries: 2,
      fifties: 2,
      color: "#6a5acd",
    },
    {
      id: "11",
      name: "Tariq",
      ranking: 11,
      matchesPlayed: 8,
      lifetimeScore: 170,
      averageScore: 21.25,
      centuries: 1,
      fifties: 1,
      color: "#7fffd4",
    },
    {
      id: "12",
      name: "Shahid",
      ranking: 12,
      matchesPlayed: 10,
      lifetimeScore: 190,
      averageScore: 19.0,
      centuries: 0,
      fifties: 2,
      color: "#ff1493",
    },
    {
      id: "13",
      name: "Hamza",
      ranking: 13,
      matchesPlayed: 6,
      lifetimeScore: 145,
      averageScore: 24.17,
      centuries: 1,
      fifties: 0,
      color: "#3cb371",
    },
    {
      id: "14",
      name: "Salman",
      ranking: 14,
      matchesPlayed: 7,
      lifetimeScore: 130,
      averageScore: 18.57,
      centuries: 0,
      fifties: 1,
      color: "#c71585",
    },
    {
      id: "15",
      name: "Zeeshan",
      ranking: 15,
      matchesPlayed: 9,
      lifetimeScore: 195,
      averageScore: 21.67,
      centuries: 1,
      fifties: 1,
      color: "#2e8b57",
    },
  ];
  
export const sampleMatches: Match[] = [
  {
    id: "1",
    player1: samplePlayers[0],
    player2: samplePlayers[1],
    player1Score: 6,
    player2Score: 13,
    date: new Date("2025-01-11"),
    tournament: "Tiger vs Lion",
    venue: "Crucible Theatre",
    winnerId: "2",
  },
  {
    id: "2",
    player1: samplePlayers[0],
    player2: samplePlayers[1],
    player1Score: 26,
    player2Score: 51,
    date: new Date("2025-01-10"),
    tournament: "Tiger vs Lion",
    venue: "Crucible Theatre",
    winnerId: "2",
  },
  {
    id: "3",
    player1: samplePlayers[2],
    player2: samplePlayers[3],
    player1Score: 199,
    player2Score: 204,
    date: new Date("2024-11-30"),
    tournament: "Bilal vs Asim",
    venue: "Alexandra Palace",
    winnerId: "4",
  },
  {
    id: "4",
    player1: samplePlayers[2],
    player2: samplePlayers[3],
    player1Score: 195,
    player2Score: 169,
    date: new Date("2024-11-29"),
    tournament: "Bilal vs Asim",
    venue: "Alexandra Palace",
    winnerId: "3",
  },
  {
    id: "5",
    player1: samplePlayers[2],
    player2: samplePlayers[3],
    player1Score: 125,
    player2Score: 193,
    date: new Date("2024-11-29"),
    tournament: "Bilal vs Asim",
    venue: "Alexandra Palace",
    winnerId: "4",
  },
  {
    id: "6",
    player1: samplePlayers[2],
    player2: samplePlayers[3],
    player1Score: 200,
    player2Score: 115,
    date: new Date("2024-11-29"),
    tournament: "Bilal vs Asim",
    venue: "Alexandra Palace",
    winnerId: "3",
  },
  {
    id: "7",
    player1: samplePlayers[4],
    player2: samplePlayers[1],
    player1Score: 200,
    player2Score: 139,
    date: new Date("2024-11-22"),
    tournament: "Chittas vs Eagles",
    venue: "York Barbican",
    winnerId: "5",
  },
  {
    id: "8",
    player1: samplePlayers[1],
    player2: samplePlayers[3],
    player1Score: 180,
    player2Score: 172,
    date: new Date("2024-10-18"),
    tournament: "Champions League",
    venue: "Sheffield Arena",
    winnerId: "2",
  },
  {
    id: "9",
    player1: samplePlayers[0],
    player2: samplePlayers[4],
    player1Score: 210,
    player2Score: 199,
    date: new Date("2024-10-15"),
    tournament: "Legends Battle",
    venue: "Cardiff Arena",
    winnerId: "1",
  },
  {
    id: "10",
    player1: samplePlayers[3],
    player2: samplePlayers[2],
    player1Score: 143,
    player2Score: 146,
    date: new Date("2024-10-14"),
    tournament: "Legends Battle",
    venue: "Cardiff Arena",
    winnerId: "3",
  },
  {
    id: "11",
    player1: samplePlayers[4],
    player2: samplePlayers[2],
    player1Score: 155,
    player2Score: 155,
    date: new Date("2024-10-01"),
    tournament: "Snooker Super Cup",
    venue: "York Hall",
    winnerId: "", // draw or no winner
  },
  {
    id: "12",
    player1: samplePlayers[0],
    player2: samplePlayers[3],
    player1Score: 167,
    player2Score: 189,
    date: new Date("2024-09-28"),
    tournament: "Euro Masters",
    venue: "Berlin Arena",
    winnerId: "4",
  },
  {
    id: "13",
    player1: samplePlayers[1],
    player2: samplePlayers[2],
    player1Score: 132,
    player2Score: 150,
    date: new Date("2024-09-26"),
    tournament: "Euro Masters",
    venue: "Berlin Arena",
    winnerId: "3",
  },
  {
    id: "14",
    player1: samplePlayers[0],
    player2: samplePlayers[2],
    player1Score: 184,
    player2Score: 160,
    date: new Date("2024-09-22"),
    tournament: "World Invitational",
    venue: "Crucible Theatre",
    winnerId: "1",
  },
  {
    id: "15",
    player1: samplePlayers[3],
    player2: samplePlayers[4],
    player1Score: 201,
    player2Score: 198,
    date: new Date("2024-09-18"),
    tournament: "World Invitational",
    venue: "Crucible Theatre",
    winnerId: "3",
  },
  {
    id: "16",
    player1: samplePlayers[1],
    player2: samplePlayers[4],
    player1Score: 188,
    player2Score: 190,
    date: new Date("2024-09-10"),
    tournament: "UK Classic",
    venue: "Manchester Central",
    winnerId: "5",
  },
  {
    id: "17",
    player1: samplePlayers[2],
    player2: samplePlayers[0],
    player1Score: 149,
    player2Score: 173,
    date: new Date("2024-09-01"),
    tournament: "UK Classic",
    venue: "Manchester Central",
    winnerId: "1",
  },
  
];
