export const sampleAllMatches = [
    {
      matchId: 1,
      date: new Date("2025-01-11"),
      teamA: "Browns",
      teamB: "Chittas",
      teamAScore: 200,
      teamBScore: 129,
      winner: "Browns",
    },
    {
      matchId: 2,
      date: new Date("2025-01-12"),
      teamA: "Falcons",
      teamB: "Wolves",
      teamAScore: 178,
      teamBScore: 182,
      winner: "Wolves",
    },
    {
      matchId: 3,
      date: new Date("2025-01-13"),
      teamA: "Sharks",
      teamB: "Tigers",
      teamAScore: 210,
      teamBScore: 190,
      winner: "Sharks",
    },
    {
      matchId: 4,
      date: new Date("2025-01-14"),
      teamA: "Eagles",
      teamB: "Browns",
      teamAScore: 175,
      teamBScore: 180,
      winner: "Browns",
    },
    {
      matchId: 5,
      date: new Date("2025-01-15"),
      teamA: "Chittas",
      teamB: "Falcons",
      teamAScore: 140,
      teamBScore: 160,
      winner: "Falcons",
    },
    {
      matchId: 6,
      date: new Date("2025-01-16"),
      teamA: "Wolves",
      teamB: "Tigers",
      teamAScore: 199,
      teamBScore: 185,
      winner: "Wolves",
    },
    {
      matchId: 7,
      date: new Date("2025-01-17"),
      teamA: "Sharks",
      teamB: "Eagles",
      teamAScore: 170,
      teamBScore: 175,
      winner: "Eagles",
    },
    {
      matchId: 8,
      date: new Date("2025-01-18"),
      teamA: "Browns",
      teamB: "Falcons",
      teamAScore: 180,
      teamBScore: 180,
      winner: "Draw",
    },
    {
      matchId: 9,
      date: new Date("2025-01-19"),
      teamA: "Chittas",
      teamB: "Wolves",
      teamAScore: 135,
      teamBScore: 210,
      winner: "Wolves",
    },
    {
      matchId: 10,
      date: new Date("2025-01-20"),
      teamA: "Tigers",
      teamB: "Eagles",
      teamAScore: 160,
      teamBScore: 158,
      winner: "Tigers",
    },
    {
      matchId: 11,
      date: new Date("2025-01-21"),
      teamA: "Sharks",
      teamB: "Browns",
      teamAScore: 190,
      teamBScore: 192,
      winner: "Browns",
    },
    {
      matchId: 12,
      date: new Date("2025-01-22"),
      teamA: "Falcons",
      teamB: "Chittas",
      teamAScore: 165,
      teamBScore: 155,
      winner: "Falcons",
    },
    {
      matchId: 13,
      date: new Date("2025-01-23"),
      teamA: "Wolves",
      teamB: "Eagles",
      teamAScore: 200,
      teamBScore: 205,
      winner: "Eagles",
    },
    {
      matchId: 14,
      date: new Date("2025-01-24"),
      teamA: "Tigers",
      teamB: "Sharks",
      teamAScore: 180,
      teamBScore: 160,
      winner: "Tigers",
    },
    {
      matchId: 15,
      date: new Date("2025-01-25"),
      teamA: "Browns",
      teamB: "Chittas",
      teamAScore: 220,
      teamBScore: 180,
      winner: "Browns",
    },
    {
      matchId: 16,
      date: new Date("2025-01-26"),
      teamA: "Falcons",
      teamB: "Wolves",
      teamAScore: 175,
      teamBScore: 170,
      winner: "Falcons",
    },
    {
      matchId: 17,
      date: new Date("2025-01-27"),
      teamA: "Eagles",
      teamB: "Tigers",
      teamAScore: 190,
      teamBScore: 190,
      winner: "Draw",
    },
    {
      matchId: 18,
      date: new Date("2025-01-28"),
      teamA: "Chittas",
      teamB: "Sharks",
      teamAScore: 145,
      teamBScore: 160,
      winner: "Sharks",
    },
    {
      matchId: 19,
      date: new Date("2025-01-29"),
      teamA: "Browns",
      teamB: "Wolves",
      teamAScore: 210,
      teamBScore: 200,
      winner: "Browns",
    },
    {
      matchId: 20,
      date: new Date("2025-01-30"),
      teamA: "Tigers",
      teamB: "Falcons",
      teamAScore: 170,
      teamBScore: 165,
      winner: "Tigers",
    },
  ];
  